// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LMessage {
    #[prost(oneof = "l_message::Extension", tags = "1")]
    pub extension: ::core::option::Option<l_message::Extension>,
}
/// Nested message and enum types in `LMessage`.
pub mod l_message {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Extension {
        #[prost(message, tag = "1")]
        MapPartition(super::LMapPartition),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LMapPartition {
    #[prost(string, tag = "1")]
    pub so_path: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub fn_name: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub output_schema: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub hash_partition_exprs: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "5")]
    pub hash_partition_count: u64,
    #[prost(bytes = "vec", tag = "6")]
    pub distribute_by_expr: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "7")]
    pub num_partitions: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PMessage {
    #[prost(oneof = "p_message::Extension", tags = "1, 2")]
    pub extension: ::core::option::Option<p_message::Extension>,
}
/// Nested message and enum types in `PMessage`.
pub mod p_message {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Extension {
        #[prost(bytes, tag = "1")]
        Opaque(::prost::alloc::vec::Vec<u8>),
        #[prost(message, tag = "2")]
        MapPartition(super::PMapPartition),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PMapPartition {
    #[prost(string, tag = "1")]
    pub so_path: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub fn_name: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub output_schema: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub hash_partition_exprs: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "5")]
    pub hash_partition_count: u64,
    #[prost(bytes = "vec", tag = "6")]
    pub distribute_by_expr: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "7")]
    pub num_partitions: u64,
}
